### ISSUE TITLE
Video Frame settings question.

### ISSUE THREAD

**Issue by dngkatn** [doughtmw/HoloLens2-Machine-Learning#3]
Dear. Michell Doughty.
Hello. I ran the sample you uploaded. I distributed it to Hololens 2, and it works very well. 
I just have a question. Is there a reason why you set the size of the video frame to (224, 224)? 
To stare at the image hololens for verification, I have to stick close to the monitor. 
Is this because of the size of the video frame? Can I increase the size of the video frame?
I look forward to hearing from you. Thank you.

**Comment by doughtmw** [comment]
Hi @dngkatn, I stuck with `224 x 224 px` video frames as they offer a good balance between model accuracy and inference speed. In this sample, I'm cropping video frames directly from their HoloLens 2 recorded resolution to `224 x 224 px` for inference. 

In another sample of mine [[link]](https://github.com/doughtmw/surgeon-assist-net), I include a C++ dll project (OpenCVRuntimeComponent) to replicate a typical image pre-processing pipeline from PyTorch training where the HoloLens 2 video frames are resized rather than cropped, resulting in much better performance.
